export interface FailureContext {
  route: string;
  lastAction: any;
  failure: {
    errors: string[];
    consoleErrors: string[];
    networkFailures: string[];
  };
}

export async function analyzeFailure(context: FailureContext): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  
  if (apiKey && apiKey !== '' && !apiKey.startsWith('your_')) {
    try {
      console.log('🤖 Invoking OpenAI GPT diagnostics engine...');
      const packageName = 'openai';
      const { default: OpenAI } = await import(packageName);
      const openai = new OpenAI({ apiKey });
      const res = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are a senior Principal QA Engineer, SRE, and Next.js Debugging Expert. Propose precise, actionable fixes for failures.'
          },
          {
            role: 'user',
            content: JSON.stringify(context, null, 2)
          }
        ]
      });
      return res.choices[0].message.content || 'No diagnosis generated by AI.';
    } catch (err: any) {
      console.warn(`⚠️ Warning: OpenAI completion failed (${err.message}). Defaulting to expert heuristic diagnosis...`);
    }
  }

  // Dual-mode SRE Fallback: Highly semantic heuristic diagnostic reports
  console.log('🛡️ Invoking Expert Heuristic Diagnostics engine (Zero-Key mode)...');
  return generateHeuristicDiagnosis(context);
}

function generateHeuristicDiagnosis(context: FailureContext): string {
  const { route, lastAction, failure } = context;
  const sections: string[] = [];

  sections.push(`======================================================================`);
  sections.push(`🔴 AI SRE FAILURE DIAGNOSIS REPORT`);
  sections.push(`======================================================================`);
  sections.push(`📍 Failed Route: ${route}`);
  sections.push(`⚙️ Last Attempted Action: ${JSON.stringify(lastAction)}`);
  sections.push(`----------------------------------------------------------------------`);

  let diagnosed = false;

  // 1. Diagnose React hydration mismatch or chunking errors
  const allConsole = failure.consoleErrors.join('\n');
  const allErrors = failure.errors.join('\n');
  
  if (allConsole.includes('hydration') || allErrors.includes('hydration') || allConsole.includes('Hydration')) {
    sections.push(`🧠 ROOT CAUSE: React Hydration Mismatch Detected!`);
    sections.push(`👉 Explanation: The client-rendered DOM differs from the pre-generated server-rendered HTML markup.`);
    sections.push(`🔧 Actionable Fix: Ensure there are no server-client state deviations (e.g., direct window/document references, using un-hydrated Date objects, or layout elements wrapping invalid HTML elements like <div> inside <p>).`);
    diagnosed = true;
  }

  // 2. Webpack runtime bundle crash
  if (allConsole.includes('Cannot read properties of undefined') || allConsole.includes('call') || allErrors.includes('loading chunk')) {
    sections.push(`🧠 ROOT CAUSE: Webpack Runtime Module Graph Corruption!`);
    sections.push(`👉 Explanation: The browser failed to load dynamic chunks, or references a module factory identifier that was destroyed/purged during compiler tree-shaking.`);
    sections.push(`🔧 Actionable Fix: Run a complete clean build. Ensure no server-side imports exist in layouts or client bundles to restore graph boundaries.`);
    diagnosed = true;
  }

  // 3. Network or API 500 crashes
  const apiFailure = failure.networkFailures.find(f => f.includes('/api/'));
  if (apiFailure) {
    sections.push(`🧠 ROOT CAUSE: Backend API Crash or Connectivity Failure!`);
    sections.push(`👉 Details: ${apiFailure}`);
    sections.push(`🔧 Actionable Fix: Check server-side endpoint logs. Ensure the local database transporter or third-party connections are active.`);
    diagnosed = true;
  }

  // 4. Contrast ratio or visual layout shifts
  if (allConsole.includes('contrast') || allConsole.includes('CLS') || allConsole.includes('layout') || allErrors.includes('contrast')) {
    sections.push(`🧠 ROOT CAUSE: Poor Color Contrast or Visual Cumulative Layout Shift (CLS)!`);
    sections.push(`👉 Explanation: Elements on the viewport shifted during paint cycles, or text elements did not satisfy WCAG 2.1 AA background contrast boundaries.`);
    sections.push(`🔧 Actionable Fix: Restrict fixed-dimension sizes on containers. Set clear fallback font faces to avoid font swap layout jank. Validate text elements carry compliant background ratio ratios.`);
    diagnosed = true;
  }

  // 5. Fallback default diagnostics
  if (!diagnosed) {
    sections.push(`🧠 DIAGNOSIS: UI Interactivity Blocked or Timeout occurred.`);
    sections.push(`👉 Details: Playwright was unable to click/locate the target element "${lastAction?.selector || 'body'}".`);
    sections.push(`🔧 Recommended Fix: Check if the selector is fully rendered. Consider using data-testid selectors to protect the element locator from structural DOM drift.`);
  }

  sections.push(`----------------------------------------------------------------------`);
  sections.push(`📊 TELEMETRY AUDITED:`);
  sections.push(`  - Unhandled Window Errors: ${failure.errors.length}`);
  sections.push(`  - Console Error Log Count: ${failure.consoleErrors.length}`);
  sections.push(`  - Network/API failures: ${failure.networkFailures.length}`);
  sections.push(`======================================================================`);

  return sections.join('\n');
}
