import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

export async function POST(req: Request) {
  try {
    const data = await req.json();
    const { companyId, iataNumber, employeeName, clientName, checkIn, checkOut, roomTypeId } = data;

    let discount = 0;
    let corporateAccount = null;
    let travelAgent = null;

    if (companyId) {
      corporateAccount = await prisma.corporateAccount.findUnique({ where: { companyName: companyId } });
      if (corporateAccount && corporateAccount.negotiatedRate) {
        discount = corporateAccount.negotiatedRate;
      }
    } else if (iataNumber) {
      travelAgent = await prisma.travelAgent.findFirst({ where: { iataNumber } });
    }

    const checkInDate = new Date(checkIn);
    const checkOutDate = new Date(checkOut);
    
    // Find available room
    const room = await prisma.room.findFirst({
      where: {
        roomTypeId,
        status: 'AVAILABLE'
      }
    });

    if (!room) {
      return NextResponse.json({ error: 'No available rooms for the selected type' }, { status: 400 });
    }

    const roomType = await prisma.roomType.findUnique({ where: { id: roomTypeId } });
    const nights = Math.ceil((checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 3600 * 24));
    let totalAmount = (roomType?.baseRate || 0) * nights;

    if (discount > 0) {
      totalAmount = totalAmount - (totalAmount * (discount / 100));
    }

    const booking = await prisma.$transaction(async (tx: any) => {
      // 1. Create or find Guest
      const guestEmail = `${clientName.replace(/\s+/g, '.').toLowerCase()}@b2b.guest.com`;
      let guest = await tx.user.findUnique({ where: { email: guestEmail } });
      
      if (!guest) {
        guest = await tx.user.create({
          data: {
            name: clientName,
            email: guestEmail,
            password: crypto.randomUUID(), // Autogenerated random password
            corporateAccountId: corporateAccount?.id,
            travelAgentId: travelAgent?.id
          }
        });
      }

      // 2. Create Booking
      const newBooking = await tx.booking.create({
        data: {
          confirmationCode: `B2B-${Date.now().toString(36).toUpperCase()}`,
          checkIn: checkInDate,
          checkOut: checkOutDate,
          roomId: room.id,
          primaryGuestId: guest.id,
          totalAmount,
          status: 'CONFIRMED',
          source: 'WEBSITE',
          paymentStatus: 'unpaid'
        }
      });

      // 3. Create Invoice
      const invoice = await tx.invoice.create({
        data: {
          invoiceNo: `INV-${newBooking.confirmationCode}`,
          bookingId: newBooking.id,
          subtotal: totalAmount,
          taxAmount: 0,
          grandTotal: totalAmount,
          status: 'DRAFT',
          folioType: 'MASTER'
        }
      });

      await tx.invoiceLineItem.create({
        data: {
          invoiceId: invoice.id,
          description: `Room Charge (${nights} nights)`,
          quantity: 1,
          unitPrice: totalAmount,
          totalPrice: totalAmount,
          category: 'ROOM',
          sourceModule: 'B2B'
        }
      });

      // 4. Update room status to reserved/expected is usually done on checkin, 
      // but we might mark the room or rely on Booking table for availability logic.
      
      return newBooking;
    });

    return NextResponse.json({ 
      success: true, 
      message: 'B2B Booking created successfully.',
      bookingId: booking.id,
      discountApplied: discount,
      agentCommissionTracked: !!travelAgent || !!iataNumber
    });

  } catch (error) {
    console.error('Failed to process B2B booking:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
