import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { enhancedRateLimit, createEnhancedRateLimitResponse } from '@/lib/rate-limit-enhanced';
import { getCached } from '@/lib/cache';

export async function POST(req: NextRequest) {
  try {
    const rateLimitResult = await enhancedRateLimit(req, 'booking');
    if (!rateLimitResult.allowed) {
      return createEnhancedRateLimitResponse(rateLimitResult);
    }

    const data = await req.json();
    const { companyId, companyEmail, iataNumber, agentEmail, employeeName, clientName, guestEmail, tosAccepted, gdprConsent, checkIn, checkOut, roomTypeId } = data;

    if (!guestEmail || tosAccepted !== true || gdprConsent !== true) {
      return NextResponse.json(
        { error: 'Missing required compliance data: guestEmail, tosAccepted, and gdprConsent are mandatory.' },
        { status: 400 }
      );
    }

    let discount = 0;
    let corporateAccount: any = null;
    let travelAgent: any = null;

    if (companyId) {
      if (!companyEmail) {
        return NextResponse.json({ error: 'companyEmail is required to validate corporate account ownership.' }, { status: 401 });
      }
      corporateAccount = await getCached(`corporateAccount:${companyId}`, () => prisma.corporateAccount.findUnique({ where: { companyName: companyId } }), 3600);
      if (!corporateAccount || corporateAccount.contactEmail !== companyEmail || !corporateAccount.isActive) {
         return NextResponse.json({ error: 'Invalid corporate account credentials or account inactive.' }, { status: 401 });
      }
      if (corporateAccount.negotiatedRate) {
        discount = corporateAccount.negotiatedRate;
      }
    } else if (iataNumber) {
      if (!agentEmail) {
        return NextResponse.json({ error: 'agentEmail is required to validate travel agent ownership.' }, { status: 401 });
      }
      travelAgent = await getCached(`travelAgent:${iataNumber}`, () => prisma.travelAgent.findFirst({ where: { iataNumber } }), 3600);
      if (!travelAgent || travelAgent.contactEmail !== agentEmail || !travelAgent.isActive) {
        return NextResponse.json({ error: 'Invalid travel agent credentials or account inactive.' }, { status: 401 });
      }
    }

    const checkInDate = new Date(checkIn);
    const checkOutDate = new Date(checkOut);
    
    // Find available room
    const room = await prisma.room.findFirst({
      where: {
        roomTypeId,
        status: 'AVAILABLE'
      }
    });

    if (!room) {
      return NextResponse.json({ error: 'No available rooms for the selected type' }, { status: 400 });
    }

    const roomType: any = await getCached(`roomType:${roomTypeId}`, () => prisma.roomType.findUnique({ where: { id: roomTypeId } }), 3600);
    const nights = Math.ceil((checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 3600 * 24));
    let totalAmount = (roomType?.baseRate || 0) * nights;

    if (discount > 0) {
      totalAmount = totalAmount - (totalAmount * (discount / 100));
    }

    const booking = await prisma.$transaction(async (tx: any) => {
      // 1. Create or find Guest
      let guest = await tx.user.findFirst({ where: { email: guestEmail, deletedAt: null } });
      
      if (!guest) {
        guest = await tx.user.create({
          data: {
            name: clientName,
            email: guestEmail,
            password: crypto.randomUUID(), // Autogenerated random password
            corporateAccountId: corporateAccount?.id,
            travelAgentId: travelAgent?.id
          }
        });
      }

      // 2. Create Booking
      const newBooking = await tx.booking.create({
        data: {
          confirmationCode: `B2B-${Date.now().toString(36).toUpperCase()}`,
          checkIn: checkInDate,
          checkOut: checkOutDate,
          roomId: room.id,
          primaryGuestId: guest.id,
          totalAmount,
          status: 'CONFIRMED',
          source: 'WEBSITE',
          paymentStatus: 'unpaid'
        }
      });

      // 3. Create Invoice
      const invoice = await tx.invoice.create({
        data: {
          invoiceNo: `INV-${newBooking.confirmationCode}`,
          bookingId: newBooking.id,
          subtotal: totalAmount,
          taxAmount: 0,
          grandTotal: totalAmount,
          status: 'DRAFT',
          folioType: 'MASTER'
        }
      });

      await tx.invoiceLineItem.create({
        data: {
          invoiceId: invoice.id,
          description: `Room Charge (${nights} nights)`,
          quantity: 1,
          unitPrice: totalAmount,
          totalPrice: totalAmount,
          category: 'ROOM',
          sourceModule: 'B2B'
        }
      });

      // 4. Update room status to reserved/expected is usually done on checkin, 
      // but we might mark the room or rely on Booking table for availability logic.
      
      return newBooking;
    });

    return NextResponse.json({ 
      success: true, 
      message: 'B2B Booking created successfully.',
      bookingId: booking.id,
      discountApplied: discount,
      agentCommissionTracked: !!travelAgent || !!iataNumber
    });

  } catch (error) {
    console.error('Failed to process B2B booking:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
