export const MOCK_ROOMS = [
  {
    id: "mock-1",
    number: "101",
    type: "STANDARD",
    capacity: 2,
    price: 150,
    description: "A comfortable standard room with modern amenities, perfect for short stays.",
    amenities: ["Free Wi-Fi", "Air Conditioning", "Flat-screen TV", "Mini-bar"],
    images: ["https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800"],
    floor: 1,
    size: 250,
    status: "AVAILABLE",
  },
  {
    id: "mock-2",
    number: "202",
    type: "DELUXE",
    capacity: 2,
    price: 250,
    description: "Spacious deluxe room featuring a king-sized bed and a beautiful city view.",
    amenities: ["Free Wi-Fi", "Air Conditioning", "Coffee Maker", "Safe", "Ocean View"],
    images: ["https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&q=80&w=800"],
    floor: 2,
    size: 350,
    status: "AVAILABLE",
  },
  {
    id: "mock-3",
    number: "303",
    type: "SUITE",
    capacity: 4,
    price: 450,
    description: "Luxurious suite with a separate living area and premium furnishings.",
    amenities: ["Free Wi-Fi", "Kitchenette", "Balcony", "Jacuzzi", "Premium Sound System"],
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800"],
    floor: 3,
    size: 600,
    status: "AVAILABLE",
  },
  {
    id: "mock-4",
    number: "404",
    type: "PRESIDENTIAL",
    capacity: 6,
    price: 1200,
    description: "Our finest suite, offering ultimate luxury, privacy, and panoramic views.",
    amenities: ["Private Elevator", "Butler Service", "Gourmet Kitchen", "Private Pool", "Library"],
    images: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800"],
    floor: 4,
    size: 1500,
    status: "AVAILABLE",
  },
  {
    id: "mock-5",
    number: "105",
    type: "STANDARD",
    capacity: 2,
    price: 150,
    description: "Cosy standard room with all the essentials for a relaxing stay.",
    amenities: ["Free Wi-Fi", "Desk", "En-suite Bathroom", "Room Service"],
    images: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=80&w=800"],
    floor: 1,
    size: 250,
    status: "OCCUPIED",
  },
  {
    id: "mock-6",
    number: "206",
    type: "DELUXE",
    capacity: 3,
    price: 280,
    description: "Deluxe family room with additional space and premium bedding.",
    amenities: ["Free Wi-Fi", "King Bed", "Sofa Bed", "City View"],
    images: ["https://images.unsplash.com/photo-1591088398332-8a77d399de75?auto=format&fit=crop&q=80&w=800"],
    floor: 2,
    size: 400,
    status: "MAINTENANCE",
  }
];
